_target_: latent_motion_tokenizer.src.models.latent_motion_tokenizer.LatentMotionTokenizer
codebook_dim: 32
commit_loss_w: 1.0
recon_loss_w: 1.0
perceptual_loss_w: 1.0
use_optical_flow: true
flow_checkpoint_path: "/home/yyang-infobai/Moto/unimatch/pretrained/gmflow-scale2-regrefine6-mixdata-train320x576-4e7b215d.pth"

image_encoder:
  _target_: transformers.ViTMAEModel.from_pretrained
  pretrained_model_name_or_path: "/home/yyang-infobai/.cache/huggingface/hub/models--facebook--vit-mae-large/snapshots/142cb8c25e1b1bc1769997a919aa1b5a2345a6b8"

m_former:
  _target_: latent_motion_tokenizer.src.models.m_former.MFormer
  add_pooling_layer: false
  use_flow: true
  config:
    _target_: transformers.ViTConfig
    query_num: 8
    input_hidden_size: 1024
    num_patches: 197 # include the [CLS] token
    attention_probs_dropout_prob: 0.0
    hidden_act: "gelu"
    hidden_dropout_prob: 0.0
    hidden_size: 768
    initializer_range: 0.02
    intermediate_size: 3072
    layer_norm_eps: 1e-12
    model_type: "vit"
    num_attention_heads: 12
    num_hidden_layers: 4
    qkv_bias: true

vector_quantizer:
  _target_: latent_motion_tokenizer.src.models.vector_quantizer.VectorQuantizer2
  n_e: 128
  e_dim: 32
  beta: 0.25
  remap: null
  sane_index_shape: true

decoder:
  _target_: latent_motion_tokenizer.src.models.latent_motion_decoder.LatentMotionDecoder
  config:
    _target_: transformers.ViTConfig
    query_num: 8
    attention_probs_dropout_prob: 0.0
    hidden_act: "gelu"
    hidden_dropout_prob: 0.0
    hidden_size: 768
    image_size: 224
    initializer_range: 0.02
    intermediate_size: 3072
    layer_norm_eps: 1e-12
    model_type: "vit"
    num_attention_heads: 12
    num_channels: 3
    num_hidden_layers: 12
    patch_size: 16
    qkv_bias: true
    encoder_stride: 16
    num_patches: 196
    query_fusion_mode: add

optical_flow_model:
  _target_: unimatch.unimatch.unimatch.UniMatch
  feature_channels: 128
  num_scales: 2
  upsample_factor: 4
  num_head: 1
  ffn_dim_expansion: 4
  num_transformer_layers: 6
  reg_refine: true
  task: "flow"

compute_flow_kwargs: {
  attn_type: "swin",
  attn_splits_list: [2, 8],
  corr_radius_list: [-1, 4],
  prop_radius_list: [-1, 1],
  num_reg_refine: 6,
  task: "flow"
}