moto_gpt_config_path: "/home/yyang-infobai/Moto/moto_gpt/configs/models/actPredTrue_motoinPredTrue_rlbench.yaml"
latent_motion_tokenizer_path: "/home/yyang-infobai/Moto/latent_motion_tokenizer/outputs/latent_motion_tokenizer_trained_on_rlbench/paired/saved_epoch_1_step_30000"
dataset_config_path: "/home/yyang-infobai/Moto/moto_gpt/configs/data/rlbench.yaml"
dataloader_config:
  bs_per_gpu: 16
  workers_per_gpu: 7
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
    use_original_rgb: False
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 200
  lr_max: 0.0002
  weight_decay: 0.0001
  gradient_accumulation_steps: 8
  save_epochs: 1
  save_steps: 10000
  save_path: "/home/yyang-infobai/Moto/moto_gpt/outputs/moto_gpt_trained_on_rlbench/paired/30000steps"
  resume_ckpt_path: null
  max_epoch: 20
  pred_binary_gripper_action: true
  use_paired_loss: true