moto_gpt_config_path: "/home/yyang-infobai/Moto/moto_gpt/configs/models/actPredTrue_motionPredTrue_metaworld.yaml"
latent_motion_tokenizer_path: "/home/yyang-infobai/Moto/latent_motion_tokenizer/outputs/ckpts/not_paired/temp_step_30000"
# dataset_config_path: "/group/40101/milkcychen/Moto/moto_gpt/configs/data/calvin.yaml"
# dataloader_config:
#   bs_per_gpu: 16
#   workers_per_gpu: 7
#   prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 1000
  num_warmup_epochs: 100
  print_steps: 100
  lr_max: 0.0002
  weight_decay: 0.0001
  gradient_accumulation_steps: 8
  save_steps: 5000
  eval_steps: 1000
  save_path: "/home/yyang-infobai/Moto/moto_gpt/outputs/moto_gpt_trained_on_metaworld/"
  resume_ckpt_path: 
  max_epoch: 
  pred_binary_gripper_action: true