paired_loss: true
paired_latent_motion_tokenizer_config_path: "/home/yyang-infobai/Moto_multiview/latent_motion_tokenizer/configs/models/model_for_calvin_paired.yaml"
not_paired_latent_motion_tokenizer_config_path: "/home/yyang-infobai/Moto_multiview/latent_motion_tokenizer/configs/models/model_for_calvin.yaml"
latent_motion_tokenizer_3d_config_path: "/home/yyang-infobai/Moto_multiview/latent_motion_tokenizer/configs/models/model_for_calvin_3d.yaml"
dataset_config_path: "/home/yyang-infobai/Moto_multiview/latent_motion_tokenizer/configs/data/calvin.yaml"
dataloader_config:
  bs_per_gpu: 32
  # bs_per_gpu: 64
  workers_per_gpu: 7
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 21
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 1
  save_steps: 1000
  save_path: "/home/yyang-infobai/Moto_multiview/latent_motion_tokenizer/outputs/calvin/paired_b32_gpu4_calvinD_D_3d/"
  resume_ckpt_path: 
  paired_method: "3d"
  lm_restrict_weight: 0.5
